# This is a basic workflow to help you get started with Actions

name: Benchmark

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ klevitz-dev ]
  pull_request:
    branches: [ klevitz-dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  cmake:
    runs-on: ubuntu-latest
    
    steps:
    # CMake build generator actions-setup-cmake (from market place)
      - name: actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v1.0
  hyperfine:
    runs-on: [ubuntu-latest]
    steps:
      - name: Install and run Hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.9.0/hyperfine_1.9.0_amd64.deb
          sudo dpkg -i hyperfine_1.9.0_amd64.deb
          hyperfine "make test"
