# This is a basic workflow to help you get started with Actions

name: Benchmark

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ klevitz-dev ]
  pull_request:
    branches: [ klevitz-dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  benchmark:
    name: Run Javascript Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run benchmark
        run:
          sudo apt-get update;
          sudo apt-get install nodejs -y;
          npm i --save benchmark;
          npm install --no-optional;
          cmake .;
          make -j all;
          node bench.js | tee output.txt;
          git stash save;
          git config --local user.email "action@github.com";
          git config --local user.name "GitHub Action";
      - name: Store benchmark result
        uses: veg/github-action-benchmark@v1
        with:
          name: Benchmark.js Benchmark
          tool: 'benchmarkjsInverse'
          output-file-path: ./output.txt
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
          github-token: ${{ secrets.benchmark }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@klevitz'
            
